language: kotlin
sudo: required
dist: trusty

jdk:
- oraclejdk8

stages:
  - name: build
  - name: benchmark
    if: type == pull_request
  - name: upload
    if: branch = master AND type != pull_request AND sender != 47degdev
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: build
      script:
        - ./gradlew clean build test
        - ./gradlew :docs:runAnk
    - stage: benchmark
      script:
        - git clone https://github.com/47deg/helios helios_master
        - cd helios_master && ./gradlew :helios-benchmarks:executeMasterBenchmark && cd ..
        - ./gradlew :helios-benchmarks:executeHeliosBenchmark
        - ./gradlew :helios-benchmarks:compareBenchmarkCI
    - stage: upload
      script:
        - ./gradlew :helios-benchmarks:executeMasterBenchmark
        - ./gradlew :helios-benchmarks:executeLibrariesBenchmark
        - ./gradlew :helios-benchmarks:uploadBenchmark
    - stage: deploy
      script:
        - ./deploy-scripts/deploy.sh
        - ./gradlew release
